variables: 
  MYVAR: "sandbox_env"

default:
  # This image used across all the stages
  image:
    name: ${SHARED_CONTAINER_REGISTRY}/glrunnerimg:$GITLAB_RUNNER_IMAGE_VERSION
  tags:
    - dev
 
stages:
  - stage1
  - stage2
  - stage3

stage1:
  stage: stage1
  script:
    - export MYVAR="SIT_env"
    - echo "MYVAR=$MYVAR"
    - echo "MYVAR=$MYVAR" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

stage2:
  stage: stage2
  needs:
    - job: stage1
      artifacts: true
  script:
    - echo "stage2 MYVAR:$MYVAR"
  environment: 
    name: $MYVAR

stage3:
  stage: stage3
  script:
    - echo "stage3 - MYVAR=$MYVAR"
  environment: 
    name: $MYVAR