variables: 
  MYVAR: "sandbox_env"
 
stages:
  - stage1
  - stage2
  - stage3

stage1:
  stage: stage1
  script:
    - $MYVAR=blabla
  artifacts:
    reports:
      dotenv: variables.env

stage2:
  stage: stage2
  needs:
    - job: stage1
      artifacts: true
  script:
    - echo "stage2 MYVAR:$MYVAR"
  environment: 
    name: $MYVAR

stage3:
  stage: stage3
  script:
    - echo "stage3 - MYVAR=$MYVAR"
  environment: 
    name: $MYVAR